# Panda Basis

## 1. Basic Data Structure: Series

1. A series object has 2 columns: index, and corresponding values.
2. Series is similar to python dictionary.
3. We can use python dictionary to create a Series object.

In [1]:
import numpy as np

import pandas as pd

In [2]:
# Create a Series

s1 = pd.Series([2,3,4])

s1

0    2
1    3
2    4
dtype: int64

In [3]:
s1.index # it returns the series s1's index

RangeIndex(start=0, stop=3, step=1)

In [4]:
s1.values # it returns the series s1's values as an array

array([2, 3, 4])

In [6]:
# create a series with specific index

s2 = pd.Series([2,3,4], index=["a","b","c"])

s2

a    2
b    3
c    4
dtype: int64

In [7]:
s2["c"] # it returns the value whose index is "c"

np.int64(4)

In [8]:
s2[["a","b"]] # it returns part of the Series s2 whose index are taken in

a    2
b    3
dtype: int64

In [9]:
# check if a specific index is in a given series

"c" in s2

True

In [10]:
"f" in s2

False

In [13]:
# Create a Series from a python dictionary

dict1 = {'Ohio':35000, 'Texas':71000, 'Oregon': 16000, 'Utah': 5000}

dict1

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [14]:
s1 = pd.Series(dict1)

s1

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
# we can build a new Series based on an existing one

states = ['California', 'Ohio', 'Oregon', 'Texas']

s2 = pd.Series(dict1, index = states)

s2

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
s2["California"] = 22223

s2

California    22223.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
states = ['New York', 'Ohio', 'Oregon', 'Texas']

s3 = pd.Series(dict1, index = states)

s3

New York        NaN
Ohio        35000.0
Oregon      16000.0
Texas       71000.0
dtype: float64

In [22]:
pd.notnull(s3)

New York    False
Ohio         True
Oregon       True
Texas        True
dtype: bool

In [23]:
pd.isnull(s3)

New York     True
Ohio        False
Oregon      False
Texas       False
dtype: bool

In [24]:
s1 + s2

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [25]:
s1 + s2 + s3

California         NaN
New York           NaN
Ohio          105000.0
Oregon         48000.0
Texas         213000.0
Utah               NaN
dtype: float64

In [26]:
s1 * 2

Ohio       70000
Texas     142000
Oregon     32000
Utah       10000
dtype: int64

In [27]:
np.exp(s1/10000) # element-wise exponential function value

Ohio        33.115452
Texas     1211.967074
Oregon       4.953032
Utah         1.648721
dtype: float64

## 2. Series reindexing

given a Series s1, s1.reindex() function takes an array of index as the argument, then returns a new Series.

In [28]:
s1 = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])

s1

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [31]:
# s1.reindex() will create a new Series

s2 = s1.reindex(["a", "b", "c", "d"])

s2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [33]:
s3 = s1.reindex(["a", "b", "c", "d", "e"], fill_value = 999)

s3

a     -5.3
b      7.2
c      3.6
d      4.5
e    999.0
dtype: float64

## 3. Drop entries from a Series

given a Series s, use a s.drop() funcion

s.drop() takes an array of index you want to drop as the argument

it returns a new series, the original series doesn't change

In [37]:
s1 = pd.Series(np.arange(5.0), index=['a','b','c','d','e'])

s1

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [38]:
s2 = s1.drop(["b", "d"])

s2

a    0.0
c    2.0
e    4.0
dtype: float64

In [39]:
s1

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

# 4. Apply a function to a Series

Given a Series s, s.map(f) returns a new Series that executed function f element-wise of s

In [40]:
def absolute(x):
    if x >= 0:
        return x
    else:
        return -x

In [41]:
absolute(-99)

99

In [42]:
s1 = pd.Series(np.random.randn(5), index = np.arange(5)+1)

s1

1    0.176850
2   -0.582230
3   -0.154535
4    1.314296
5   -2.207554
dtype: float64

In [43]:
s2 = s1.map(absolute)
s2

1    0.176850
2    0.582230
3    0.154535
4    1.314296
5    2.207554
dtype: float64

In [45]:
s1 # s1 doesn't change

1    0.176850
2   -0.582230
3   -0.154535
4    1.314296
5   -2.207554
dtype: float64

## 5. Series Sorting adn Ranking

Given a Series s

s.sort_index(): sorted by index, return a new Series, the original s doesn't change

s.sort_value(): sorted by values, return a new Series, the original s doesn't change

In [47]:
s = pd.Series(np.random.randn(5), index = np.random.permutation(np.arange(5)+1))

s

5    0.072378
4   -0.891877
1    0.563353
2    0.820688
3    0.850104
dtype: float64

In [49]:
s1 = s.sort_index()

s1

1    0.563353
2    0.820688
3    0.850104
4   -0.891877
5    0.072378
dtype: float64

In [50]:
s2 = s.sort_values()

s2

4   -0.891877
5    0.072378
1    0.563353
2    0.820688
3    0.850104
dtype: float64

In [51]:
s.sum()

np.float64(1.4146460636723415)

In [52]:
s.mean()

np.float64(0.2829292127344683)

In [53]:
s.std()

np.float64(0.7269818653049067)

In [54]:
s.var()

np.float64(0.5285026324822015)

In [55]:
s.describe()

count    5.000000
mean     0.282929
std      0.726982
min     -0.891877
25%      0.072378
50%      0.563353
75%      0.820688
max      0.850104
dtype: float64

In [56]:
s.idxmax()

np.int64(3)

In [57]:
s.idxmin()

np.int64(4)

In [58]:
s.max()

np.float64(0.8501037292344341)

In [59]:
s.min()

np.float64(-0.8918769462455034)

# 8. Unique Values, Value Counts and Membership on Series

In [4]:
import numpy as np

import pandas as pd

In [5]:
s1 = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

s1

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: str

In [6]:
# s1.unique()  this returns an array

uniques = s1.unique()

uniques

<ArrowStringArray>
['c', 'a', 'd', 'b']
Length: 4, dtype: str

In [7]:
# s1.value_counts()  this returns a Series

s1.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [8]:
# s1.isin()  it takesw an array as an argument and returns a Series of boolean values

s1.isin(["b", "c"])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

# Basic Data Structure: Data Frame

1. Create a data frame from dictionary
2. Create a data frame from a 2d array

In [9]:
# create array from a dictionary

dict1 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
         'year': [2000, 2001, 2002, 2001, 2002],
         'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

frame = pd.DataFrame(dict1)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [10]:
frame2 = pd.DataFrame(dict1, columns = ["year", "pop", "state"]) # specify the order of the columns

frame2

   year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada

In [46]:
frame3 = pd.DataFrame(dict1,
                       columns = ["year", "pop", "state", "debt"],
                       index = np.arange(5)+1) # specify the index starting from 1
frame3

   year  pop   state debt
1  2000  1.5    Ohio  NaN
2  2001  1.7    Ohio  NaN
3  2002  3.6    Ohio  NaN
4  2001  2.4  Nevada  NaN
5  2002  2.9  Nevada  NaN

In [47]:
# Create a data frame from a 2D array

arr1 =np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
frame4 = pd.DataFrame(arr1,
                      index = ["c", "a", "e"],
                      columns = ["Ohio", "texas", "california"])

frame4

   Ohio  texas  california
c     0      1           2
a     3      4           5
e     6      7           8

## 10. Data Frame Column and Row Operation

1. each column of a dataframe i a Series: frame.year; frame["year"]
2. each row of a dataframe is also a Series: frame.ix[2]

In [49]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [50]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [51]:
frame.pop

<bound method DataFrame.pop of     state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9>

In [52]:
frame["pop"]

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

In [53]:
frame.loc[2]

state    Ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [54]:
frame3

   year  pop   state debt
1  2000  1.5    Ohio  NaN
2  2001  1.7    Ohio  NaN
3  2002  3.6    Ohio  NaN
4  2001  2.4  Nevada  NaN
5  2002  2.9  Nevada  NaN

In [55]:
frame3.debt

1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
Name: debt, dtype: object

In [56]:
frame3.debt = 12 # assign valus to a specific column

frame3

   year  pop   state  debt
1  2000  1.5    Ohio    12
2  2001  1.7    Ohio    12
3  2002  3.6    Ohio    12
4  2001  2.4  Nevada    12
5  2002  2.9  Nevada    12

In [57]:
frame3.debt = np.arange(5) + 3

frame3

   year  pop   state  debt
1  2000  1.5    Ohio     3
2  2001  1.7    Ohio     4
3  2002  3.6    Ohio     5
4  2001  2.4  Nevada     6
5  2002  2.9  Nevada     7

In [58]:
frame["balance"] = 10000 # generate a new column called "balance" and assign the calues to this column

frame3

   year  pop   state  debt
1  2000  1.5    Ohio     3
2  2001  1.7    Ohio     4
3  2002  3.6    Ohio     5
4  2001  2.4  Nevada     6
5  2002  2.9  Nevada     7

## Data Frame Reindexing

In [8]:
import numpy as np
import pandas as pd

given a data frame df1

1. df1.reindex() takes a list as an argument
2. it returns a NEW data frame, and the df1 doesn't change.
3. you can reindex index, or you can reindex the columns.

In [14]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3),
                   index = ["a", "c", "d"],
                   columns = ["Ohio", "Texas", "California"])

df1

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [15]:
df2 = df1.reindex(["a", "b", "c", "d"])

df2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [16]:
df1

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [17]:
# reindex the columns

new_columns = ["Ohio", "Utah", "California"]

df3 = df1.reindex(columns = new_columns)

df3

   Ohio  Utah  California
a     0   NaN           2
c     3   NaN           5
d     6   NaN           8

## 12. Drop Items or Columns from a Data Frame

given a data frame df1
1. df1.drop() takes a list as an argument
2. axis = 1 means drop columns
3. the method returns a new edata frame, the df1 doesn't change

In [20]:
df1 = pd.DataFrame(np.arange(16).reshape(4,4),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])

df1

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [23]:
df2 = df1.drop(["Ohio", "Utah"])

df2

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [25]:
df3 = df1.drop(["one", "three"], axis = 1)

df3

          two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

## 13. Data Frame indexing, selection and filtering

In [26]:
df1

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
df1.loc["Ohio"] # it returns a series

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [31]:
df1.loc[["Ohio"]] # it returns a data frame

      one  two  three  four
Ohio    0    1      2     3

In [32]:
df1["one"]

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [34]:
df1[["one"]]

          one
Ohio        0
Colorado    4
Utah        8
New York   12

In [35]:
df1.iloc[:,[0]]

          one
Ohio        0
Colorado    4
Utah        8
New York   12

In [36]:
df1

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
df1[df1["three"]>5] # select all the data such that the column "three" value are greater than 5

# single condition

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [42]:
df1[(df1["one"]>1) & (df1["four"] <13)]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11